export default {
    "cities": {
        "a": [{
            "id": 56,
            "spell": "aba",
            "name": "阿坝"
        }, {
            "id": 57,
            "spell": "akesu",
            "name": "阿克苏"
        }, {
            "id": 58,
            "spell": "alashanmeng",
            "name": "阿拉善盟"
        }, {
            "id": 59,
            "spell": "aletai",
            "name": "阿勒泰"
        }, {
            "id": 60,
            "spell": "ali",
            "name": "阿里"
        }, {
            "id": 61,
            "spell": "ankang",
            "name": "安康"
        }, {
            "id": 62,
            "spell": "anqing",
            "name": "安庆"
        }, {
            "id": 63,
            "spell": "anshan",
            "name": "鞍山"
        }, {
            "id": 64,
            "spell": "anshun",
            "name": "安顺"
        }, {
            "id": 65,
            "spell": "anyang",
            "name": "安阳"
        }, {
            "id": 338,
            "spell": "acheng",
            "name": "阿城"
        }, {
            "id": 339,
            "spell": "anfu",
            "name": "安福"
        }, {
            "id": 340,
            "spell": "anji",
            "name": "安吉"
        }, {
            "id": 341,
            "spell": "anning",
            "name": "安宁"
        }, {
            "id": 342,
            "spell": "anqiu",
            "name": "安丘"
        }, {
            "id": 343,
            "spell": "anxi",
            "name": "安溪"
        }, {
            "id": 344,
            "spell": "anyi",
            "name": "安义"
        }, {
            "id": 345,
            "spell": "anyuan",
            "name": "安远"
        }],
        "b": [{
            "id": 1,
            "spell": "beijing",
            "name": "北京"
        }, {
            "id": 66,
            "spell": "baicheng",
            "name": "白城"
        }, {
            "id": 67,
            "spell": "baise",
            "name": "百色"
        }, {
            "id": 68,
            "spell": "baishan",
            "name": "白山"
        }, {
            "id": 69,
            "spell": "baiyin",
            "name": "白银"
        }, {
            "id": 70,
            "spell": "bangbu",
            "name": "蚌埠"
        }, {
            "id": 71,
            "spell": "baoding",
            "name": "保定"
        }, {
            "id": 72,
            "spell": "baoji",
            "name": "宝鸡"
        }, {
            "id": 73,
            "spell": "baoshan",
            "name": "保山"
        }, {
            "id": 74,
            "spell": "baotou",
            "name": "包头"
        }, {
            "id": 75,
            "spell": "bayannaoer",
            "name": "巴彦淖尔"
        }, {
            "id": 76,
            "spell": "bayinguoleng",
            "name": "巴音郭楞"
        }, {
            "id": 77,
            "spell": "bazhong",
            "name": "巴中"
        }, {
            "id": 78,
            "spell": "beihai",
            "name": "北海"
        }, {
            "id": 79,
            "spell": "benxi",
            "name": "本溪"
        }, {
            "id": 80,
            "spell": "bijie",
            "name": "毕节"
        }, {
            "id": 81,
            "spell": "binzhou",
            "name": "滨州"
        }, {
            "id": 82,
            "spell": "boertala",
            "name": "博尔塔拉"
        }, {
            "id": 83,
            "spell": "bozhou",
            "name": "亳州"
        }, {
            "id": 346,
            "spell": "baoying",
            "name": "宝应"
        }, {
            "id": 347,
            "spell": "bayan",
            "name": "巴彦"
        }, {
            "id": 348,
            "spell": "binhai",
            "name": "滨海"
        }, {
            "id": 349,
            "spell": "binxian",
            "name": "宾县"
        }, {
            "id": 350,
            "spell": "binyang",
            "name": "宾阳"
        }, {
            "id": 351,
            "spell": "bishan",
            "name": "璧山"
        }, {
            "id": 352,
            "spell": "boai",
            "name": "博爱"
        }, {
            "id": 353,
            "spell": "boluo",
            "name": "博罗"
        }, {
            "id": 354,
            "spell": "boxing",
            "name": "博兴"
        }],
        "c": [{
            "id": 2,
            "spell": "chongqing",
            "name": "重庆"
        }, {
            "id": 5,
            "spell": "changchun",
            "name": "长春"
        }, {
            "id": 6,
            "spell": "changsha",
            "name": "长沙"
        }, {
            "id": 7,
            "spell": "changzhou",
            "name": "常州"
        }, {
            "id": 8,
            "spell": "chengdu",
            "name": "成都"
        }, {
            "id": 84,
            "spell": "cangzhou",
            "name": "沧州"
        }, {
            "id": 85,
            "spell": "changde",
            "name": "常德"
        }, {
            "id": 86,
            "spell": "changdu",
            "name": "昌都"
        }, {
            "id": 87,
            "spell": "changji",
            "name": "昌吉"
        }, {
            "id": 88,
            "spell": "changzhi",
            "name": "长治"
        }, {
            "id": 89,
            "spell": "chaohu",
            "name": "巢湖"
        }, {
            "id": 90,
            "spell": "chaoyang",
            "name": "朝阳"
        }, {
            "id": 91,
            "spell": "chaozhou",
            "name": "潮州"
        }, {
            "id": 92,
            "spell": "chengde",
            "name": "承德"
        }, {
            "id": 93,
            "spell": "chenzhou",
            "name": "郴州"
        }, {
            "id": 94,
            "spell": "chifeng",
            "name": "赤峰"
        }, {
            "id": 95,
            "spell": "chizhou",
            "name": "池州"
        }, {
            "id": 96,
            "spell": "chongzuo",
            "name": "崇左"
        }, {
            "id": 97,
            "spell": "chuxiong",
            "name": "楚雄"
        }, {
            "id": 98,
            "spell": "chuzhou",
            "name": "滁州"
        }, {
            "id": 355,
            "spell": "cangnan",
            "name": "苍南"
        }, {
            "id": 356,
            "spell": "cangshan",
            "name": "苍山"
        }, {
            "id": 357,
            "spell": "caoxian",
            "name": "曹县"
        }, {
            "id": 358,
            "spell": "changdao",
            "name": "长岛"
        }, {
            "id": 359,
            "spell": "changfeng",
            "name": "长丰"
        }, {
            "id": 360,
            "spell": "changhai",
            "name": "长海"
        }, {
            "id": 361,
            "spell": "changle",
            "name": "长乐"
        }, {
            "id": 362,
            "spell": "changle",
            "name": "昌乐"
        }, {
            "id": 363,
            "spell": "changshan",
            "name": "常山"
        }, {
            "id": 364,
            "spell": "changshu",
            "name": "常熟"
        }, {
            "id": 365,
            "spell": "changtai",
            "name": "长泰"
        }, {
            "id": 366,
            "spell": "changting",
            "name": "长汀"
        }, {
            "id": 367,
            "spell": "changxing",
            "name": "长兴"
        }, {
            "id": 368,
            "spell": "changyi",
            "name": "昌邑"
        }, {
            "id": 369,
            "spell": "chaoan",
            "name": "潮安"
        }, {
            "id": 370,
            "spell": "chenggong",
            "name": "呈贡"
        }, {
            "id": 371,
            "spell": "chengkou",
            "name": "城口"
        }, {
            "id": 372,
            "spell": "chengwu",
            "name": "成武"
        }, {
            "id": 373,
            "spell": "chiping",
            "name": "茌平"
        }, {
            "id": 374,
            "spell": "chongren",
            "name": "崇仁"
        }, {
            "id": 375,
            "spell": "chongyi",
            "name": "崇义"
        }, {
            "id": 376,
            "spell": "chongzhou",
            "name": "崇州"
        }, {
            "id": 377,
            "spell": "chunan",
            "name": "淳安"
        }, {
            "id": 378,
            "spell": "cixi",
            "name": "慈溪"
        }, {
            "id": 379,
            "spell": "conghua",
            "name": "从化"
        }, {
            "id": 380,
            "spell": "congyang",
            "name": "枞阳"
        }],
        "d": [{
			"id": 9,
			"spell": "dalian",
			"name": "大连"
		}, {
			"id": 10,
			"spell": "dongguan",
			"name": "东莞"
		}, {
			"id": 99,
			"spell": "dali",
			"name": "大理"
		}, {
			"id": 100,
			"spell": "dandong",
			"name": "丹东"
		}, {
			"id": 101,
			"spell": "daqing",
			"name": "大庆"
		}, {
			"id": 102,
			"spell": "datong",
			"name": "大同"
		}, {
			"id": 103,
			"spell": "daxinganling",
			"name": "大兴安岭"
		}, {
			"id": 104,
			"spell": "dazhou",
			"name": "达州"
		}, {
			"id": 105,
			"spell": "dehong",
			"name": "德宏"
		}, {
			"id": 106,
			"spell": "deyang",
			"name": "德阳"
		}, {
			"id": 107,
			"spell": "dezhou",
			"name": "德州"
		}, {
			"id": 108,
			"spell": "dingxi",
			"name": "定西"
		}, {
			"id": 109,
			"spell": "diqing",
			"name": "迪庆"
		}, {
			"id": 110,
			"spell": "dongying",
			"name": "东营"
		}, {
			"id": 381,
			"spell": "dafeng",
			"name": "大丰"
		}, {
			"id": 382,
			"spell": "daishan",
			"name": "岱山"
		}, {
			"id": 383,
			"spell": "dangshan",
			"name": "砀山"
		}, {
			"id": 384,
			"spell": "dangtu",
			"name": "当涂"
		}, {
			"id": 385,
			"spell": "danxian",
			"name": "单县"
		}, {
			"id": 386,
			"spell": "danyang",
			"name": "丹阳"
		}, {
			"id": 387,
			"spell": "dapu",
			"name": "大埔"
		}, {
			"id": 388,
			"spell": "datian",
			"name": "大田"
		}, {
			"id": 389,
			"spell": "dayi",
			"name": "大邑"
		}, {
			"id": 390,
			"spell": "dayu",
			"name": "大余"
		}, {
			"id": 391,
			"spell": "dazu",
			"name": "大足"
		}, {
			"id": 392,
			"spell": "dean",
			"name": "德安"
		}, {
			"id": 393,
			"spell": "dehua",
			"name": "德化"
		}, {
			"id": 394,
			"spell": "dehui",
			"name": "德惠"
		}, {
			"id": 395,
			"spell": "dengfeng",
			"name": "登封"
		}, {
			"id": 396,
			"spell": "deqing",
			"name": "德清"
		}, {
			"id": 397,
			"spell": "deqing",
			"name": "德庆"
		}, {
			"id": 398,
			"spell": "dexing",
			"name": "德兴"
		}, {
			"id": 399,
			"spell": "dianbai",
			"name": "电白"
		}, {
			"id": 400,
			"spell": "dianjiang",
			"name": "垫江"
		}, {
			"id": 401,
			"spell": "dingnan",
			"name": "定南"
		}, {
			"id": 402,
			"spell": "dingtao",
			"name": "定陶"
		}, {
			"id": 403,
			"spell": "dingyuan",
			"name": "定远"
		}, {
			"id": 404,
			"spell": "donga",
			"name": "东阿"
		}, {
			"id": 405,
			"spell": "donghai",
			"name": "东海"
		}, {
			"id": 406,
			"spell": "dongming",
			"name": "东明"
		}, {
			"id": 407,
			"spell": "dongping",
			"name": "东平"
		}, {
			"id": 408,
			"spell": "dongshan",
			"name": "东山"
		}, {
			"id": 409,
			"spell": "dongtai",
			"name": "东台"
		}, {
			"id": 410,
			"spell": "dongtou",
			"name": "洞头"
		}, {
			"id": 411,
			"spell": "dongxiang",
			"name": "东乡"
		}, {
			"id": 412,
			"spell": "dongyang",
			"name": "东阳"
		}, {
			"id": 413,
			"spell": "dongyuan",
			"name": "东源"
		}, {
			"id": 414,
			"spell": "dongzhi",
			"name": "东至"
		}, {
			"id": 415,
			"spell": "duchang",
			"name": "都昌"
		}, {
			"id": 416,
			"spell": "dujiangyan",
			"name": "都江堰"
		}],
		"e": [{
			"id": 111,
			"spell": "eerduosi",
			"name": "鄂尔多斯"
		}, {
			"id": 112,
			"spell": "enshi",
			"name": "恩施"
		}, {
			"id": 113,
			"spell": "ezhou",
			"name": "鄂州"
		}, {
			"id": 417,
			"spell": "enping",
			"name": "恩平"
		}],
		"f": [{
			"id": 11,
			"spell": "foshan",
			"name": "佛山"
		}, {
			"id": 12,
			"spell": "fuzhou",
			"name": "福州"
		}, {
			"id": 114,
			"spell": "fangchenggang",
			"name": "防城港"
		}, {
			"id": 115,
			"spell": "fushun",
			"name": "抚顺"
		}, {
			"id": 116,
			"spell": "fuxin",
			"name": "阜新"
		}, {
			"id": 117,
			"spell": "fuyang",
			"name": "阜阳"
		}, {
			"id": 118,
			"spell": "fuzhou",
			"name": "抚州"
		}, {
			"id": 418,
			"spell": "faku",
			"name": "法库"
		}, {
			"id": 419,
			"spell": "fanchang",
			"name": "繁昌"
		}, {
			"id": 420,
			"spell": "fangzheng",
			"name": "方正"
		}, {
			"id": 421,
			"spell": "feicheng",
			"name": "肥城"
		}, {
			"id": 422,
			"spell": "feidong",
			"name": "肥东"
		}, {
			"id": 423,
			"spell": "feixi",
			"name": "肥西"
		}, {
			"id": 424,
			"spell": "feixian",
			"name": "费县"
		}, {
			"id": 425,
			"spell": "fengcheng",
			"name": "丰城"
		}, {
			"id": 426,
			"spell": "fengdu",
			"name": "丰都"
		}, {
			"id": 427,
			"spell": "fenghua",
			"name": "奉化"
		}, {
			"id": 428,
			"spell": "fengjie",
			"name": "奉节"
		}, {
			"id": 429,
			"spell": "fengkai",
			"name": "封开"
		}, {
			"id": 430,
			"spell": "fengshun",
			"name": "丰顺"
		}, {
			"id": 431,
			"spell": "fengtai",
			"name": "凤台"
		}, {
			"id": 432,
			"spell": "fengxian",
			"name": "丰县"
		}, {
			"id": 433,
			"spell": "fengxin",
			"name": "奉新"
		}, {
			"id": 434,
			"spell": "fengyang",
			"name": "凤阳"
		}, {
			"id": 435,
			"spell": "fenyi",
			"name": "分宜"
		}, {
			"id": 436,
			"spell": "fogang",
			"name": "佛冈"
		}, {
			"id": 437,
			"spell": "fuan",
			"name": "福安"
		}, {
			"id": 438,
			"spell": "fuding",
			"name": "福鼎"
		}, {
			"id": 439,
			"spell": "fuliang",
			"name": "浮梁"
		}, {
			"id": 440,
			"spell": "fumin",
			"name": "富民"
		}, {
			"id": 441,
			"spell": "funan",
			"name": "阜南"
		}, {
			"id": 442,
			"spell": "funing",
			"name": "阜宁"
		}, {
			"id": 443,
			"spell": "fuqing",
			"name": "福清"
		}, {
			"id": 444,
			"spell": "fuyang",
			"name": "富阳"
		}]
    }
}